format:
  html: {toc: true, toc-depth: 4, theme: cosmo}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: Studying layoffs in tech in 2024
  chapters: [index.qmd, notebooks.layoffs.qmd]
